# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsGallery', '0002_auto_20161218_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='uploads/', verbose_name='img'),
        ),
    ]
