# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_color',
            field=models.CharField(choices=[('e5e5e5', 'Cream'), ('222222', 'Dark')], default='e5e5e5', max_length=6),
        ),
    ]
