# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 21:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetup', '0006_auto_20161217_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 17, 22, 35, 1, 584692)),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_title',
            field=models.CharField(choices=[('About Us', 'about_us'), ('Our Work', 'our_work'), ('Contact Us', 'contact_us')], max_length=50),
        ),
    ]
