# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 21:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetup', '0007_auto_20161217_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 17, 22, 36, 9, 721641)),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_title',
            field=models.CharField(choices=[('about_us', 'About Us'), ('our_work', 'Our Work'), ('contact_us', 'Contact Us')], max_length=50),
        ),
    ]
