# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 21:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetup', '0008_auto_20161217_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_num', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 17, 22, 41, 24, 146021)),
        ),
        migrations.AddField(
            model_name='contactform',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteSetup.Section'),
        ),
    ]
