# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 21:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetup', '0012_auto_20161217_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 17, 22, 56, 54, 599086)),
        ),
    ]
