# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 11:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetup', '0023_auto_20161218_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 18, 12, 36, 27, 723045)),
        ),
    ]
